# Generated by Django 5.2.7 on 2025-10-27 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='adress',
            new_name='address',
        ),
    ]
