# Generated by Django 5.2.7 on 2025-10-27 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_rename_adress_wallet_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='address',
            new_name='adress',
        ),
    ]
